version: "3.9"

networks:
  my_network:
    driver: bridge

services:
  manager:
    image: mrlarryman/umasscybersec-ccdc-docker-training:manager
    container_name: manager
    hostname: manager
    networks:
      - my_network
    ports:
      - "5601:5601"
      - "9200:9200"
      - "1514:1514/udp"
      - "6067:443"
      - "7067:80"
      - "8067:22"
    environment:
      - TZ=UTC
    restart: unless-stopped

  server:
    image: mrlarryman/umasscybersec-ccdc-docker-training:server
    container_name: server
    hostname: server
    ports: # host port : internal port
      - "5067:443"
      - "4067:80"
      - "3067:22"
    networks:
      - my_network
    depends_on:
      - manager
    environment:
      - MANAGER_HOST=manager
      - TZ=UTC
    restart: unless-stopped
